theme = "modern"
icons = "awesome"

[[block]]
block = "focused_window"
max_width = 60
show_marks = "visible"

[[block]]
block = "music"
buttons = ["play", "next"]

[[block]]
block = "pomodoro"
length = 25
break_length = 5
message = "Take a break!"
break_message = "Back to work!"
use_nag = true
nag_path = "i3-nagbar"

[[block]]
block = "cpu"
interval = 1

[[block]]
block = "disk_space"
info_type = "available"

[[block]]
block = "docker"
interval = 2
format = "{running}/{total}"

[[block]]
block = "backlight"
device = "intel_backlight"

[[block]]
block = "sound"

[[block]]
block = "battery"
interval = 10

[[block]]
block = "time"
interval = 60
format = "%a %d/%m %R"

[[block]]
block = "notify"
